variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_STRATEGY: clone  

image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - Build
  - Run

build_job:
  stage: Build
  script:
    - docker login -u "$name" --password "$password"
    - docker build -t dmajoros/mycv:latest -f Dockerfile .
    - docker image ls
    - docker push dmajoros/mycv:latest
    - docker logout

run_job:
  stage: Run
  script:
    - docker login -u "$name" --password "$password"
    - docker run --name testimage -p 8004:80 -dit dmajoros/mycv:latest
    - docker logout
