variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_STRATEGY: clone  

image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - Build

build_job:
  stage: Build
  script:
    - echo "$password" | docker login -u "$name" --password-stdin
    - docker build -t dmajoros/mycv:latest -f Dockerfile .
    - docker image ls
    - docker push dmajoros/mycv:latest
    - docker logout

#ahoj
