#variables:
 # GIT_SSL_NO_VERIFY: "true"

# This is test pipeline

# Stages
stages: 
  - BUILD 
  - DEPLOY 

# Jobs
build_job:
  stage: BUILD  
  script:
  - echo "Welcome from build_job." 
  - ls -la
  - echo "done" 

# Info
doploy_job:
    stage: DEPLOY
    script:
    - echo "Welcome from deploy_job."
    - date
    - echo "done"

