variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_STRATEGY: clone  

image: docker
services:
  - docker:dind

stages:
  - Build
  - Run

build_job:
  stage: Build
  tags:
    - dmajoros
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t dmajoros/mycv:latest -f Dockerfile .
    - docker image ls
    - docker push dmajoros/mycv:latest
    - docker logout

run_job:
  stage: Run
  tags:
    - dmajoros
  script:
    - docker stop mycv
    - docker rm mycv
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull dmajoros/mycv:latest
    - docker run --name CVcko -p 8004:80 -d dmajoros/mycv:latest
    - docker logout

