variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_STRATEGY: clone

image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - Build

build_job:
  stage: Build
  script:
    - echo "$DOCKERPWD" | docker login -u "$DOCKERUSER" --password-stdin
    - docker build -t dmajoros/mycvimage:new -f Dockerfile .
    - docker image ls
    - docker push dmajoros/mycvimage:new
    - docker logout

#ahoj
