# This is test pipeline

# Stages
stages: 
  - welcome
  - info

# Jobs
welcom_here:
  stage: welcome  
  script:
  - echo "Welcome to Docker image build job......." 
  - hostname
  - date
  - pwd 
  - echo "done" 

# Info
info_script:
    stage: info
    script:
    - echo "Your hostname is:"
    - hostname
    - echo "Date is:"
    - date
    - echo "Your currently path is:"
    - pwd
    - echo Done

