variables:
    GIT_SSL_NO_VERIFY: "true"
    GIT_STRATEGY: clone
    GIT_CONFIG: git config --unset http.proxy
    

image: docker:19.03.12
services:
  - docker:19.03.12-dind

stages:
  - Build

build_job:
  stage: Build
  script:
    - echo "$DOCKERPWD" | docker login -u "$DOCKERUSER" --password-stdin
    - docker build -t dmajoros/mycv:latest -f Dockerfile .
    - docker image ls
    - docker push dmajoros/mycv:latest
    - docker logout

#ahoj
